name: Deploy documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'backend/app/**/*.py'
      - '.forgejo/workflows/docs.yml'

permissions:
  contents: write

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref }}
  cancel-in-progress: true

jobs:

  deploy:

    runs-on: codeberg-small

    steps:
      - name: Checkout code
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: https://data.forgejo.org/actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'
          cache: pip

      - name: Install documentation dependencies
        run: pip install mkdocs-material mkdocstrings[python]

      - name: Build documentation
        run: mkdocs build --site-dir site

      - name: Deploy documentation to Codeberg Pages
        uses: https://data.forgejo.org/actions/git-pages@5978530ffb9bbe196ad9fdc0c48fdaf1483de4cf # v2.1.0
        with:
          site: https://docs.endurain.com/
          server: codeberg.page
          token: ${{ forge.token }}
          source: site/