"""your_migration_message

Revision ID: 895a29b12c8c
Revises: 262ec21a6c15
Create Date: 2026-01-22 09:13:56.378498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "895a29b12c8c"
down_revision: Union[str, None] = "262ec21a6c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_fasting",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_fasting belongs",
        ),
        sa.Column(
            "date",
            sa.Date(),
            nullable=False,
            comment="Calendar date of the fasting session",
        ),
        sa.Column(
            "fast_start_time_utc",
            sa.DateTime(),
            nullable=False,
            comment="Start time of fast in UTC",
        ),
        sa.Column(
            "fast_end_time_utc",
            sa.DateTime(),
            nullable=True,
            comment="End time of fast in UTC (null if ongoing)",
        ),
        sa.Column(
            "fast_start_time_local",
            sa.DateTime(),
            nullable=True,
            comment="Start time of fast in local timezone",
        ),
        sa.Column(
            "fast_end_time_local",
            sa.DateTime(),
            nullable=True,
            comment="End time of fast in local timezone",
        ),
        sa.Column(
            "target_duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Target fasting duration in seconds",
        ),
        sa.Column(
            "actual_duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Actual fasting duration in seconds",
        ),
        sa.Column(
            "fasting_type",
            sa.String(length=20),
            nullable=True,
            comment="Type of fasting protocol (16:8, 18:6, etc.)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Status: in_progress, completed, broken, cancelled",
        ),
        sa.Column(
            "timezone",
            sa.String(length=50),
            nullable=True,
            comment="User timezone for local time display",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Optional notes about the fasting session",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=True,
            comment="Data source (manual, garmin, etc.)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_fasting_date"), "health_fasting", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_health_fasting_user_id"), "health_fasting", ["user_id"], unique=False
    )
    op.add_column(
        "health_targets",
        sa.Column(
            "fasting",
            sa.Integer(),
            nullable=True,
            comment="Target fasting duration in seconds",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_targets", "fasting")
    op.drop_index(op.f("ix_health_fasting_user_id"), table_name="health_fasting")
    op.drop_index(op.f("ix_health_fasting_date"), table_name="health_fasting")
    op.drop_table("health_fasting")
    # ### end Alembic commands ###
