"""v0.18.0 migration

Revision ID: 895a29b12c8c
Revises: 262ec21a6c15
Create Date: 2026-01-22 09:13:56.378498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "895a29b12c8c"
down_revision: Union[str, None] = "262ec21a6c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create health_fasting table
    op.create_table(
        "health_fasting",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_fasting belongs",
        ),
        sa.Column(
            "fast_start_time",
            sa.DateTime(),
            nullable=False,
            comment="Start time of fast",
        ),
        sa.Column(
            "fast_end_time",
            sa.DateTime(),
            nullable=True,
            comment="End time of fast (null if ongoing)",
        ),
        sa.Column(
            "target_duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Target fasting duration in seconds",
        ),
        sa.Column(
            "actual_duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Actual fasting duration in seconds",
        ),
        sa.Column(
            "fasting_type",
            sa.String(length=20),
            nullable=True,
            comment="Type of fasting protocol (16:8, 18:6, etc.)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Status: in_progress, completed, broken, cancelled",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Optional notes about the fasting session",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=True,
            comment="Data source (manual, garmin, etc.)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_fasting_user_id"), "health_fasting", ["user_id"], unique=False
    )
    # Add fasting target column to health_targets table
    op.add_column(
        "health_targets",
        sa.Column(
            "fasting",
            sa.Integer(),
            nullable=True,
            comment="Target fasting duration in seconds",
        ),
    )
    # Add users_api_keys table
    op.create_table(
        "users_api_keys",
        sa.Column(
            "id",
            sa.String(length=36),
            nullable=False,
            comment="Unique key identifier (UUID4)",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the API key belongs to",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="User-friendly label for the key",
        ),
        sa.Column(
            "key_prefix",
            sa.String(length=8),
            nullable=False,
            comment="First 8 chars of the random key part, used for UI identification",
        ),
        sa.Column(
            "key_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hex digest of the full raw key",
        ),
        sa.Column(
            "scopes",
            sa.Text(),
            nullable=False,
            comment="JSON-encoded list of granted scope strings",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=True,
            comment="Key expiration timestamp (NULL = no expiry)",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp of last successful authentication",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Key creation timestamp",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the key is active. False = revoked (soft delete)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_api_keys_key_hash"), "users_api_keys", ["key_hash"], unique=True
    )
    op.create_index(
        op.f("ix_users_api_keys_user_id"), "users_api_keys", ["user_id"], unique=False
    )
    # Add map_thumbnail_path column to activities table
    op.add_column(
        "activities",
        sa.Column(
            "map_thumbnail_path",
            sa.String(length=500),
            nullable=True,
            comment="Relative path to the pre-generated static map thumbnail image",
        ),
    )
    # Add tileserver_regenerate_thumbnails_on_change column to server_settings
    op.add_column(
        "server_settings",
        sa.Column(
            "tileserver_regenerate_thumbnails_on_change",
            sa.Boolean(),
            nullable=True,
            comment=(
                "Delete and regenerate all activity thumbnails when "
                "tile server settings change"
            ),
        ),
    )
    op.execute(
        """
        UPDATE server_settings
        SET tileserver_regenerate_thumbnails_on_change = false
        WHERE tileserver_regenerate_thumbnails_on_change IS NULL;
    """
    )
    op.alter_column(
        "server_settings",
        "tileserver_regenerate_thumbnails_on_change",
        nullable=False,
        comment=(
            "Delete and regenerate all activity thumbnails when "
            "tile server settings change"
        ),
        existing_type=sa.Boolean(),
    )
    # Update comments for notifications table columns
    op.alter_column(
        "migrations",
        "executed",
        existing_type=sa.BOOLEAN(),
        comment="Whether the migration was executed",
        existing_comment="Whether the migration was executed or not",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="User ID that the notification belongs to",
        existing_comment="User ID that the gear belongs to",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.alter_column(
        "password_reset_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status",
        existing_comment="Token usage status (False - unused, True - used)",
        existing_nullable=False,
    )
    op.alter_column(
        "sign_up_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status",
        existing_comment="Token usage status (False - unused, True - used)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert comments for notifications table columns
    op.alter_column(
        "sign_up_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status (False - unused, True - used)",
        existing_comment="Token usage status",
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status (False - unused, True - used)",
        existing_comment="Token usage status",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="User ID that the gear belongs to",
        existing_comment="User ID that the notification belongs to",
        existing_nullable=False,
    )
    op.alter_column(
        "migrations",
        "executed",
        existing_type=sa.BOOLEAN(),
        comment="Whether the migration was executed or not",
        existing_comment="Whether the migration was executed",
        existing_nullable=False,
    )
    # Drop map_thumbnail_path column from activities table
    op.drop_column("activities", "map_thumbnail_path")
    # Drop tileserver_regenerate_thumbnails_on_change column from server_settings
    op.drop_column("server_settings", "tileserver_regenerate_thumbnails_on_change")
    # Drop users_api_keys table
    op.drop_index(op.f("ix_users_api_keys_user_id"), table_name="users_api_keys")
    op.drop_index(op.f("ix_users_api_keys_key_hash"), table_name="users_api_keys")
    op.drop_table("users_api_keys")
    # Drop fasting column from health_targets table
    op.drop_column("health_targets", "fasting")
    # Drop health_fasting table
    op.drop_index(op.f("ix_health_fasting_user_id"), table_name="health_fasting")
    op.drop_table("health_fasting")
    # ### end Alembic commands ###
